apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvdlpsecurityrules
rules:
- apiGroups:  [ "neuvector.com" ]
  resources: [ "nvdlpsecurityrules" ]
  verbs: [ "list", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvdlpsecurityrules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvdlpsecurityrules
subjects:
- kind: ServiceAccount
  name: default
  namespace: neuvector-system