apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvdlpsecurityrules
rules:
- apiGroups:  [" neuvector.com" ]
  resources: [ "nvdlpsecurityrules" ]
  verbs: [ "list", "delete" ]