# Tolerations to allow scheduling Enforcer pods on Control Plane nodes will vary across k8s distributions 
# so homework may be required.  Below tolerations are for RKE2/k3s.  For RKE1, change "control-plane" to "controlplane".
enforcer:
  image:
    repository: neuvector/enforcer
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
