manager:
  image:
    repository: neuvector/manager
  env:
    ssl: false
  ingress:
    enabled: true
    host: sslip.io
    path: "/"
    secretName: neuvector-ui-cert
    tls: true
  svc:
    type: ClusterIP
