manager:
  image:
    repository: rancher/mirrored-neuvector-manager
  env:
    ssl: false
  ingress:
    enabled: true
    host: neuvector.felab.io
    path: "/"
    secretName: neuvector-ui-cert
    tls: true
  svc:
    type: ClusterIP
